server:
  rootPath: "/api/"
  registerDefaultExceptionMappers: false
  applicationConnectors:
  - type: "https"
    port: "${PING_PORT:-8443}"
    keyStoreType: "PKCS12"
    keyStorePath: "config/keystorenew.p12"
    keyStorePassword: "2b952f58"
    certAlias: "server-cert"
    validateCerts: false
    validatePeers: false
  adminConnectors:
  - type: "https"
    bindHost: "localhost"
    port: "${PING_ADMIN_PORT:-8444}"
    keyStoreType: "PKCS12"
    keyStorePath: "config/admin-keystorenew.p12"
    keyStorePassword: "d62deb43"
    certAlias: "admin-cert"
    validateCerts: false
    validatePeers: false
core:
  Database.Type: "${PING_DB_TYPE:-H2}"
  Database.Driver: "${PING_DB_DRIVER:-org.h2.Driver}"
  Database.ConnectionString: "jdbc:h2:file:/opt/out/instance/./Symphonic;ALIAS_COLUMN_NAME=TRUE"
  Database.User: "${PING_DB_APP_USERNAME:-pap_user}"
  Database.Password: "${PING_DB_APP_PASSWORD:-Symphonic2014!}"
  Authentication.DecisionPoint.Protocol: "shared secret"
  Authentication.SharedSecret: "${PING_SHARED_SECRET:-2FederateM0re}"
  License.Path: "PingAuthorize.lic"
  DecisionResponse.AuditLogView: "Errors,Statements,EncryptSecrets,EvaluationLog,Request"
  DecisionPoint.EnableShortcircuiting: true
  SelfGovernance.Enabled: "${PING_SELF_GOVERNANCE_ENABLED:-false}"
  SelfGovernance.Permissions: "${PING_SELF_GOVERNANCE_PERMISSIONS_ENABLED:-false}"
  SelfGovernance.SystemUsername: "${PING_SELF_GOVERNANCE_SYSTEM_USERNAME:-SYSTEM}"
  DeploymentPackage.ContentType: "JSON"
  Ping.Database.Backup.Schedule: "${PING_BACKUP_SCHEDULE:-0 0 0 * * ?}"
  Database.Backup.H2.Directory: "${PING_H2_BACKUP_DIR:-./policy-backup}"
  Database.Backup.H2.Mode: "file"
enableUIServing: true
enableSwagger: "true"
enabledFeatures:
- "test-suite"
- "entity-dependents"
ui:
  REST_URL: "https://${PING_EXTERNAL_BASE_URL:-localhost:8443}/api/"
  statements:
  - "config/advice/add-filter.json"
  - "config/advice/combine-scim-search-authorizations.json"
  - "config/advice/custom-advice.json"
  - "config/advice/denied-reason.json"
  - "config/advice/exclude-attributes.json"
  - "config/advice/filter-response.json"
  - "config/advice/include-attributes.json"
  - "config/advice/modify-attributes.json"
  - "config/advice/modify-query.json"
  - "config/advice/modify-headers.json"
  - "config/advice/modify-scim-patch.json"
  - "config/advice/regex-replace-attributes.json"
  additionalVersion:
    applicationName: "PingAuthorize Policy Editor"
    version: "9.0.0.0"
  selfGovernance:
    permissions: "${PING_SELF_GOVERNANCE_PERMISSIONS_ENABLED:-false}"
    roles: "${PING_SELF_GOVERNANCE_ROLES:-Role 1,Role 2,Role 3}"
  authType: "credentials"
  usernames: "${PING_USERNAMES:-admin}"
logging:
  level: "INFO"
  loggers:
    DataNucleus: "ERROR"
    DataNucleus.Enhancer: "OFF"
    org.glassfish.jersey.internal.Errors: "ERROR"
    com.symphonicsoft.policyanalysis.PolicyTranslator: "ERROR"
    DECISION_AUDIT_LOG:
      level: "INFO"
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/decision-audit.log"
        archive: true
        maxFileSize: "250MB"
        archivedLogFilenamePattern: "logs/decision-audit.%i.log.gz"
        archivedFileCount: 10
        logFormat: "[%date{ISO8601}] %msg%n"
    DECISION_DIAGNOSTIC_LOG:
      level: "OFF"
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/decision-diagnostic.log"
        archive: true
        maxFileSize: "250MB"
        archivedLogFilenamePattern: "logs/decision-audit.%i.log.gz"
        archivedFileCount: 10
        logFormat: "%msg%n"
    MANAGEMENT_AUDIT:
      level: "INFO"
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/management-audit.log"
        archive: false
        archivedLogFilenamePattern: "logs/management-audit.%i.log.gz"
        archivedFileCount: 10
        logFormat: "[%date{ISO8601}] %msg%n"
    metrics:
      additive: false
      appenders:
      - type: "file"
        currentLogFilename: "logs/metrics.log"
        maxFileSize: "250MB"
        archive: true
        archivedLogFilenamePattern: "logs/metrics.%i.log.gz"
        archivedFileCount: 10
        logFormat: "logger=metrics, timestamp=%date{yyyyMMdd'T'HHmmss.SSS}, %msg%n"
  appenders:
  - type: "console"
    threshold: "INFO"
    target: "stdout"
    logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
  - type: "file"
    threshold: "DEBUG"
    currentLogFilename: "logs/debug.log"
    maxFileSize: "250MB"
    archive: true
    archivedLogFilenamePattern: "logs/debug.%i.log.gz"
    archivedFileCount: 10
    logFormat: "%-5level [%date{ISO8601}] [%thread] %c: %msg%n"
  - type: "file"
    threshold: "INFO"
    currentLogFilename: "logs/authorize-pe.log"
    maxFileSize: "250MB"
    archive: true
    archivedLogFilenamePattern: "logs/authorize-pe.%i.log.gz"
    archivedFileCount: 10
    logFormat: "%-5level [%date{ISO8601}] %c: %msg%n"
